// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using otoservistakipprogrami2025.DAL;

#nullable disable

namespace otoservistakipprogrami2025.Migrations
{
    [DbContext(typeof(OtoServisDbContext))]
    [Migration("20250623001702_InitialCreate2")]
    partial class InitialCreate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("otoservistakipprogrami2025.Models.Arac", b =>
                {
                    b.Property<int>("AracId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AracId"));

                    b.Property<string>("AracMarka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AracModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AracModelYili")
                        .HasColumnType("int");

                    b.Property<string>("AracMotorNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AracPlaka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AracRenk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AracSasiNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.HasKey("AracId");

                    b.HasIndex("MusteriId");

                    b.ToTable("Araclar");
                });

            modelBuilder.Entity("otoservistakipprogrami2025.Models.Musteri", b =>
                {
                    b.Property<int>("MusteriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MusteriId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MusteriId");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("otoservistakipprogrami2025.Models.Parca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ParcaAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParcaKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StokMiktari")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Parcalar");
                });

            modelBuilder.Entity("otoservistakipprogrami2025.Models.ParcaKullanimi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Miktar")
                        .HasColumnType("int");

                    b.Property<int>("ParcaId")
                        .HasColumnType("int");

                    b.Property<int>("ServisKaydiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParcaId");

                    b.HasIndex("ServisKaydiId");

                    b.ToTable("ParcaKullanimlari");
                });

            modelBuilder.Entity("otoservistakipprogrami2025.Models.ServisKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AracId")
                        .HasColumnType("int");

                    b.Property<string>("GelisSebebi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GelisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("ServisDurumu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TeslimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ToplamTutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("YapilanIslemler")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AracId");

                    b.ToTable("ServisKayitlari");
                });

            modelBuilder.Entity("otoservistakipprogrami2025.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("otoservistakipprogrami2025.Models.Arac", b =>
                {
                    b.HasOne("otoservistakipprogrami2025.Models.Musteri", "Musteri")
                        .WithMany("Araclar")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("otoservistakipprogrami2025.Models.ParcaKullanimi", b =>
                {
                    b.HasOne("otoservistakipprogrami2025.Models.Parca", "Parca")
                        .WithMany("Kullanimlar")
                        .HasForeignKey("ParcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("otoservistakipprogrami2025.Models.ServisKaydi", "ServisKaydi")
                        .WithMany("KullanilanParcalar")
                        .HasForeignKey("ServisKaydiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parca");

                    b.Navigation("ServisKaydi");
                });

            modelBuilder.Entity("otoservistakipprogrami2025.Models.ServisKaydi", b =>
                {
                    b.HasOne("otoservistakipprogrami2025.Models.Arac", "Arac")
                        .WithMany("ServisKayitlari")
                        .HasForeignKey("AracId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arac");
                });

            modelBuilder.Entity("otoservistakipprogrami2025.Models.Arac", b =>
                {
                    b.Navigation("ServisKayitlari");
                });

            modelBuilder.Entity("otoservistakipprogrami2025.Models.Musteri", b =>
                {
                    b.Navigation("Araclar");
                });

            modelBuilder.Entity("otoservistakipprogrami2025.Models.Parca", b =>
                {
                    b.Navigation("Kullanimlar");
                });

            modelBuilder.Entity("otoservistakipprogrami2025.Models.ServisKaydi", b =>
                {
                    b.Navigation("KullanilanParcalar");
                });
#pragma warning restore 612, 618
        }
    }
}
